AWSTemplateFormatVersion: 2010-09-09
Description: eventbridge-ssm-runsh-on-ec2

Parameters:
  Env:
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "stg", "prd"]
  ResourceName:
    Type: String
    Default: "ssm-runsh-on-ec2"
  cron:
    Type: String
    Default: "cron(25 8 * * ? *)" #JST17:25
  TargetEC2InstanceId:
    Type: AWS::EC2::Instance::Id
  AccountId:
    Type: String
  ShPath:
    Type: String
    Default: "/home/ec2-user/test/"
  ShName:
    Type: String
    Default: "test.sh"

Resources:
  EventRule:
    Type: AWS::Events::Rule
    Properties: 
      Name: !Sub "${Env}-eventbridge-${ResourceName}"
      EventBusName: default
      ScheduleExpression: !Ref cron
      State: ENABLED
      Targets:
        - Id: Id3e53de3b-8aaf-4622-a351-cd3eef85ff4b
          Arn: arn:aws:ssm:ap-northeast-1::document/AWS-RunShellScript
          RoleArn: !GetAtt EventBridgeRole.Arn
          Input: !Sub >-
            {"commands":["sudo -u ec2-user bash ${ShPath}${ShName}" ],"workingDirectory":["${ShPath}"]}
          RunCommandParameters:
            RunCommandTargets:
              - Key: InstanceIds
                Values:
                  - !Ref TargetEC2InstanceId
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Env}-role-eventbridge-${ResourceName}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
                - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${Env}-policy-eventbridge-${ResourceName}"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: sendcommand
                Effect: Allow
                Action: ssm:SendCommand
                Resource:
                  - !Sub "arn:aws:ec2:ap-northeast-1:${AccountId}:instance/${TargetEC2InstanceId}"
                  - arn:aws:ssm:ap-northeast-1:*:document/AWS-RunShellScript

